## Overlay makefile for building styles, themes and dreams
#
# Prebuilt files to copy
PRODUCT_COPY_FILES += \
    vendor/fontage/fonts/prebuilt/fonts_customization.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/fonts_customization.xml \
    vendor/fontage/fonts/prebuilt/gobold/Gobold.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Gobold.ttf \
    vendor/fontage/fonts/prebuilt/gobold/Gobold-Italic.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Gobold-Italic.ttf \
    vendor/fontage/fonts/prebuilt/gobold/GoboldBold.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/GoboldBold.ttf \
    vendor/fontage/fonts/prebuilt/gobold/GoboldBold-Italic.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/GoboldBold-Italic.ttf \
    vendor/fontage/fonts/prebuilt/gobold/GoboldThinLight.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/GoboldThinLight.ttf \
    vendor/fontage/fonts/prebuilt/gobold/GoboldThinLight-Italic.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/GoboldThinLight-Italic.ttf \
    vendor/fontage/fonts/prebuilt/roadrage/road_rage.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/RoadRage-Regular.ttf \
    vendor/fontage/fonts/prebuilt/snowstorm/snowstorm.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Snowstorm-Regular.ttf \
    vendor/fontage/fonts/prebuilt/googlesans/GoogleSans-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/GoogleSans-Regular.ttf \
    vendor/fontage/fonts/prebuilt/googlesans/GoogleSans-Medium.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/GoogleSans-Medium.ttf \
    vendor/fontage/fonts/prebuilt/fontage/AlienLeague-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/AlienLeague-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontage/BigNoodleTilting-Italic.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/BigNoodleTilting-Italic.ttf \
    vendor/fontage/fonts/prebuilt/fontage/BigNoodleTilting-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/BigNoodleTilting-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontage/Biko-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Biko-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontage/GinoraSans-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/GinoraSans-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontage/Riviera-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Riviera-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontage/Union-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Union-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev2/AdventPro-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/AdventPro-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev2/Bariol-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Bariol-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev2/CherrySwash-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/CherrySwash-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev2/din1451alt.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/din1451alt.ttf \
    vendor/fontage/fonts/prebuilt/fontagev2/Hanken-Light.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Hanken-Light.ttf \
    vendor/fontage/fonts/prebuilt/fontagev2/ReemKufi-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/ReemKufi-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev2/Vibur.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Vibur.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/AuthenticSans-Medium.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/AuthenticSans-Medium.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/AuthenticSans-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/AuthenticSans-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/ComicNeue-Bold.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/ComicNeue-Bold.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/ComicNeue-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/ComicNeue-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/Decalotype-Medium.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Decalotype-Medium.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/Decalotype-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Decalotype-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/Exo2-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Exo2-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/Exo2-SemiBold.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Exo2-SemiBold.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/FantasqueMono-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/FantasqueMono-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/Fleuron-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Fleuron-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/Finlandica-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Finlandica-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/Gothamono-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Gothamono-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/Gravity-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Gravity-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/IgnazioText-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/IgnazioText-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/Inter-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Inter-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/Inter-MediumItalic.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Inter-MediumItalic.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/JakartaPlus-Medium.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/JakartaPlus-Medium.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/JakartaPlus-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/JakartaPlus-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/LeagueMono-RegularNarrow.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/LeagueMono-RegularNarrow.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/LeagueMono-MediumNarrow.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/LeagueMono-MediumNarrow.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/LeagueMono-BoldNarrow.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/LeagueMono-BoldNarrow.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/LeagueMono-SemiBoldNarrow.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/LeagueMono-SemiBoldNarrow.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/LeonSans-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/LeonSans-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/Lumie-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Lumie-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/mescla_regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/mescla_regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/Millimetre-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Millimetre-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/Now-Medium.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Now-Medium.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/Now-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Now-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/OdibeeSans-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/OdibeeSans-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/OpenSauceSans-Medium.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/OpenSauceSans-Medium.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/OpenSauceSans-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/OpenSauceSans-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/Panamericana-Display.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Panamericana-Display.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/PTSans-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/PTSans-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/PTMono-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/PTMono-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/QTVagaRound-Bold.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/QTVagaRound-Bold.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/QTVagaRound-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/QTVagaRound-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/routed-gothic-narrow.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/routed-gothic-narrow.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/routed-gothic-narrow-half-italic.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/routed-gothic-narrow-half-italic.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/Scientifica-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Scientifica-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/SofiaSans-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/SofiaSans-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/SofiaSans-Medium.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/SofiaSans-Medium.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/Universalis-Bold.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Universalis-Bold.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/Universalis-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Universalis-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/VG5000-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/VG5000-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev3/Vladisvostok-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Vladisvostok-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4lock/3DIsometric-Black.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/3DIsometric-Black.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4lock/3DIsometric-Bold.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/3DIsometric-Bold.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4lock/BalticBodden.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/BalticBodden.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4lock/BalticCoast.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/BalticCoast.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4lock/BalticDune.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/BalticDune.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4lock/BalticStorm.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/BalticStorm.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4lock/Cafe24Decoshadow.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Cafe24Decoshadow.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4lock/Cat.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Cat.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4lock/Concentrate.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Concentrate.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4lock/Forta.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Forta.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4lock/KarmaticArcade.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/KarmaticArcade.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4lock/LiquidCrystal-Bold.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/LiquidCrystal-Bold.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4lock/MuseoModerno.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/MuseoModerno.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4lock/mx-wasgard.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/mx-wasgard.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4lock/NeptunCAT.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/NeptunCAT.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4lock/PermanentMarker.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/PermanentMarker.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4lock/ProdeltCo.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/ProdeltCo.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4lock/Rubik-Glitch-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Rubik-Glitch-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4lock/Tourney-Medium.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Tourney-Medium.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4/Blazma-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Blazma-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4/Cardelina.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Cardelina.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4/CookieRun-Bold.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/CookieRun-Bold.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4/CookieRun-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/CookieRun-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4/Gemsbuck01-Bold.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Gemsbuck01-Bold.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4/GiganticFS.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/GiganticFS.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4/Hezaedrus-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Hezaedrus-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4/HyperwaveDisplay.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/HyperwaveDisplay.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4/Jicaleta-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Jicaleta-Regular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4/JUSTSansExBold.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/JUSTSansExBold.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4/JUSTSansRegular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/JUSTSansRegular.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4/punk-mono-extendedmedium.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/punk-mono-extendedmedium.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4/punk-mono-medium.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/punk-mono-medium.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4/punk-mono-oblique.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/punk-mono-oblique.ttf \
    vendor/fontage/fonts/prebuilt/fontagev4/punk-mono-regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/punk-mono-regular.ttf \
    vendor/fontage/fonts/prebuilt/circularp404/Circular-Std-Bold.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Circular-Std-Bold.ttf \
    vendor/fontage/fonts/prebuilt/circularp404/Circular-Std-BoldItalic.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Circular-Std-BoldItalic.ttf \
    vendor/fontage/fonts/prebuilt/circularp404/Circular-Std-Italic.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Circular-Std-Italic.ttf \
    vendor/fontage/fonts/prebuilt/circularp404/Circular-Std-Medium.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Circular-Std-Medium.ttf \
    vendor/fontage/fonts/prebuilt/circularp404/Circular-Std-MediumItalic.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Circular-Std-MediumItalic.ttf \
    vendor/fontage/fonts/prebuilt/circularp404/Circular-Std-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Circular-Std-Regular.ttf \
    vendor/fontage/fonts/prebuilt/atkinson/AtkinsonHyperlegible-Bold.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/AtkinsonHyperlegible-Bold.ttf \
    vendor/fontage/fonts/prebuilt/atkinson/AtkinsonHyperlegible-BoldItalic.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/AtkinsonHyperlegible-BoldItalic.ttf \
    vendor/fontage/fonts/prebuilt/atkinson/AtkinsonHyperlegible-Italic.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/AtkinsonHyperlegible-Italic.ttf \
    vendor/fontage/fonts/prebuilt/atkinson/AtkinsonHyperlegible-Regular.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/AtkinsonHyperlegible-Regular.ttf \
    vendor/fontage/fonts/prebuilt/iosfontfamily/SFRoundedTime-Medium.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/SFRoundedTime-Medium.ttf \
    vendor/fontage/fonts/prebuilt/iosfontfamily/SFSoftTime-Semibold.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/SFSoftTime-Semibold.ttf \
    vendor/fontage/fonts/prebuilt/iosfontfamily/26FGalaxySans.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/26FGalaxySans.ttf \
    vendor/fontage/fonts/prebuilt/iosfontfamily/Alexana.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Alexana.ttf \
    vendor/fontage/fonts/prebuilt/iosfontfamily/Exodar.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/Exodar.ttf \
    vendor/fontage/fonts/prebuilt/iosfontfamily/KroppenFwO.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/KroppenFwO.ttf \
    vendor/fontage/fonts/prebuilt/iosfontfamily/KroppenOutline.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/KroppenOutline.ttf \
    vendor/fontage/fonts/prebuilt/iosfontfamily/KroppenRound.ttf:$(TARGET_COPY_OUT_PRODUCT)/fonts/KroppenRound.ttf

# Fonts required overlays packages
PRODUCT_PACKAGES += \
    FontAtkinsonOverlay \
    FontAltAtkinsonOverlay \
    FontAuthenticSansOverlay \
    FontBigNoodleOverlay \
    FontBikoHankenOverlay \
    FontComicNeueOverlay \
    FontDecalotypeOverlay \
    FontExo2Overlay \
    FontFantasqueSansMonoOverlay \
    FontFleuronOverlay \
    FontFinlandicaOverlay \
    FontGoogleSansOverlay \
    FontGothamonoOverlay \
    FontGravityOverlay \
    FontIgnazioTextOverlay \
    FontInterOverlay \
    FontJakartaPlusOverlay \
    FontLeagueMonoNarrowOverlay \
    FontLeonSansOverlay \
    FontLumieOverlay \
    FontMesclaOverlay \
    FontMilimetreOverlay \
    FontMittelschriftOverlay \
    FontNowOverlay \
    FontOpenSauceOverlay \
    FontPanamericanaOverlay \
    FontPisselOverlay \
    FontPTSansMonoOverlay \
    FontQTVagaroundOverlay \
    FontReemKufiOverlay \
    FontRobotoOverlay \
    FontRouterGothicNarrowOverlay \
    FontScientificaOverlay \
    FontSofiaSansOverlay \
    FontUniversalisRegOverlay \
    FontVladivostokOverlay \
    FontCircularStdOverlay \
    FontBlazmaHyperwaveOverlay \
    FontCardelinaOverlay \
    FontCookieRunOverlay \
    FontGemsbuckPunkMonoObliqueOverlay \
    FontGiganticFSHezaedrusOverlay \
    FontJicaletaOverlay \
    FontJustSansOverlay \
    FontPunkMonoOverlay \
    FontRalewayOverlay \

# Lockscreen clock fonts
PRODUCT_PACKAGES += \
    ClockFont26FGalaxySansOverlay \
    ClockFontAlexanaOverlay \
    ClockFontExodarOverlay \
    ClockFontKroppenFwOOverlay \
    ClockFontKroppenOutlineOverlay \
    ClockFontKroppenRoundOverlay \
    ClockFontCatOverlay \
    ClockFontConcentrateOverlay \
    ClockFontKarmaticArcadeOverlay \
    ClockFontLiquidCrystalOverlay \
    ClockFontAdventProOverlay \
    ClockFontAtkinsonOverlay \
    ClockFontBigNoodleTiltingOverlay \
    ClockFontCherrySwashOverlay \
    ClockFontHeadlineOverlay \
    ClockFontRoadRageOverlay \
    ClockFontSnowstormOverlay \
    ClockFontViburOverlay \
    ClockFontAlienLeagueOverlay \
    ClockFontOdibeeSansOverlay \
    ClockFontBikoOverlay \
    ClockFontGinoraSansOverlay \
    ClockFontPermanentMarkerOverlay \
    ClockFontRivieraOverlay \
    ClockFontSFRoundedTimeOverlay \
    ClockFontSFSoftTimeOverlay \
    ClockFontUnionOverlay \
    ClockFontVG5000Overlay \
    ClockFont3DIsometricBlackOverlay \
    ClockFont3DIsometricBoldOverlay \
    ClockFontBalticBoddenOverlay \
    ClockFontBalticCoastOverlay \
    ClockFontBalticDuneOverlay \
    ClockFontBalticStormOverlay \
    ClockFontCafe24DecoshadowOverlay \
    ClockFontFortaOverlay \
    ClockFontMuseoModernoOverlay \
    ClockFontMXWasgardOverlay \
    ClockFontNeptunCATOverlay \
    ClockFontProdeltCoOverlay \
    ClockFontRubikGlitchOverlay \
    ClockFontTourneyMediumOverlay \
    ClockFontRaleway \
